# Generated by Django 5.2.3 on 2025-06-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('people_count', models.IntegerField(default=1)),
                ('service_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('birthday', 'Tug‘ilgan kun'), ('other', 'Boshqa')], max_length=50)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(default='kutilmoqda', max_length=20)),
            ],
        ),
    ]
